// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX66-zukijGUGxOkUJYiwOAEfLslLN6rk',
    appId: '1:965166224403:web:586170b2a828cb6e571be6',
    messagingSenderId: '965166224403',
    projectId: 'fgbksr',
    authDomain: 'fgbksr.firebaseapp.com',
    storageBucket: 'fgbksr.firebasestorage.app',
    measurementId: 'G-89T1906RL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0qy0ihE1rwWw9SUEhz8rBLwn2ygoXA0',
    appId: '1:965166224403:android:3d1958345ff063c9571be6',
    messagingSenderId: '965166224403',
    projectId: 'fgbksr',
    storageBucket: 'fgbksr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB594xzBuvAORYm2Y_737U-5xCPzB2SEnI',
    appId: '1:965166224403:ios:43e18d4465f4471a571be6',
    messagingSenderId: '965166224403',
    projectId: 'fgbksr',
    storageBucket: 'fgbksr.firebasestorage.app',
    iosBundleId: 'com.example.fungibiteKasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB594xzBuvAORYm2Y_737U-5xCPzB2SEnI',
    appId: '1:965166224403:ios:43e18d4465f4471a571be6',
    messagingSenderId: '965166224403',
    projectId: 'fgbksr',
    storageBucket: 'fgbksr.firebasestorage.app',
    iosBundleId: 'com.example.fungibiteKasir',
  );
}
